### ISSUE TITLE
你好 我想请问一下这个可以直接使用已有的haar模型，还是需要重新训练一下？还有代码中的CvHaarEvaluator::Feature::Feature()中的部分形参为什么没有用到

### ISSUE THREAD

**Issue by zaidao2023** [NanKeRen2020/wavelet_adboost_detection#1]
haarfeatures.cpp 第375行
rect[3].r.x = x2;
    rect[3].r.y = y2;
    rect[3].r.width  = w2;
    rect[3].r.height = h2;
    rect[3].weight   = wt2;

**Comment by NanKeRen2020** [comment]
1. 是的，如果想用小波特征模板，则需要重新训练。
2. 代码这个地方有问题，修改成
    rect[3].r.x = x3;
    rect[3].r.y = y3;
    rect[3].r.width  = w3;
    rect[3].r.height = h3;
    rect[3].weight   = wt3;
    后面rect[]类似修改，很久的代码，上传没检查出来，谢谢指出
